[libraries]
kotlin-bom = "org.jetbrains.kotlin:kotlin-bom:2.0.20"
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.8.1"
guice = "com.google.inject:guice:7.0.0"
guava = "com.google.guava:guava:32.0.1-jre" # Guava brought in by Guice has a vulnerability, so we exclude Guava from Guice, and bring in the newer Guava with the vulnerability fix.

# Testing Libraries
assertj = "org.assertj:assertj-core:3.26.3"
mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:5.4.0"

[plugins]
kotlin = "org.jetbrains.kotlin.jvm:2.0.20"